### ISSUE TITLE
[Question]: Qgis Desktop plugin > 4.2.7 don't work with Qgis 3.18.3

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#4556]
### What is the question? (in English)

Hello
due to lack of human resources we have an old version of Qgis server (3.18.x) and I use qgis 3.18.3 on my desktop to publish projects on our server.
Lizmap Web client is 3.5.16

I found the last working Lizmap Plugin with qgis 3.18 is 4.2.7. All other versions, when I click pon the lizmap plugin button, give me a python error like this:
` WARNING    Traceback (most recent call last):
              File "C:\Users/XXXXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 5036, in run
              self.check_webdav()
              File "C:\Users/XXXXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 1149, in check_webdav
              self.webdav.config_project()
             AttributeError: 'NoneType' object has no attribute 'config_project'`

Is it normal? Must I stick to 4.2.7 until we upgrade our qgis server/Lizmap web client?
Thanks

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.5.16
* Lizmap plugin : 4.2.7
* QGIS Desktop : 3.18.3
* QGIS Server and plugins unknown status because of the settings in QGIS Server, please review your server settings in the Lizmap Web Client administration interface, then in the "Server Information" panel.

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Plugin on windows 10 x64

### Browsers

Chrome

### Browsers version

Opera last version

### Relevant log output

```shell
WARNING    Traceback (most recent call last):
              File "C:\Users/XXXXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 5036, in run
              self.check_webdav()
              File "C:\Users/XXXXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 1149, in check_webdav
              self.webdav.config_project()
             AttributeError: 'NoneType' object has no attribute 'config_project
```
